kind: Deployment
apiVersion: apps/v1
metadata:
  name: vignette
  namespace: mskh
  labels:
    app.kubernetes.io/name: vignette
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vignette
  template:
    metadata:
      labels:
        app: vignette
    spec:
      volumes:
        - name: data
          hostPath:
            path: /var/www/volumes/site-data/vignette
            type: DirectoryOrCreate
      containers:
        - name: vignette
          image: "tserobyan/school-vignette:latest"
          env:
            - name: DBURI
              value: "mongodb://root:root@mongo:27017/vignette?authSource=admin"
          volumeMounts:
            - mountPath: /app/public/images
              name: data
---
kind: Service
apiVersion: v1
metadata:
  name: vignette
  namespace: mskh
  labels:
    app.kubernetes.io/name: vignette
  annotations:
    description: "https://github.com/tserobyan/school-vignette"
spec:
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: vignette
